# Data sources

The data for this project is sourced from the World Bank. The World Bank is a group dedicated to providing high-quality statistical data on numerous topics globally to aid development and policy making. A lot of the information within the World Bank’s databases come directly from the statistical systems of member countries, which means the accuracy of the information is heavily dependent on how well these national systems perform their data collection. As a result, a high priority of the World Bank is to help improve statistical infrastructures of developing countries by preparing national strategies for the development of statistics “as recommended in the Marrakech Action Plan for Statistics”. Data collection is currently a joint effort between the World Bank and many other international statistical communities including the United Nations (UN), the Organization for Economic Co-Operation and Development (OECD), the International Monetary Fund (IMF), and regional development banks. Transnational data is also collected by the World Bank through globally coordinated programs like the Marrakech Action Plan for Statistics and PARIS21.  

For all the data collected, the World Bank ensures data consistency and reliability through:  
  -	Participation in the UN Statistical Commission and other statistical forums to develop appropriate frameworks, guidance, and standards of good practice for statistics  
  -	Building consensus and defining internationally agreed indicators such as the indicators for the Millennium Development Goals  
  -	Establishing data exchange processes and methods  
  -	Assembling, analyzing, and disseminating data online and in print  

The gender statistics data used for this project has 164,112 rows and 66 columns. Each entry represents a single indicator for a country. In total, there are 263 countries and each has 624 different indicators. Each indicator is a record item, eg. GDP, and have numeric data recorded from 1960 to 2020 (with more missing values in older years). In each row, it has 4 string variables: country name, country code, a description of indicator, and an indicator code. Some indicators have a boolean form like the yes or no statement, with the numeric data entries 1 as yes, 0 as no. The indicators can be categorized into 5 types.  
  
1) General information about the country, like GDP, fertility rate, poverty, population  
2) Education related items, like school enrollment  
3) Employment and unemployment  
4) Specific female social status indicator, like if a women can apply a passport in a same way as a man  
5) Health related indicator, like life expectancy and rate of overweight  

One problem in this data file is the high proportion of missing values. It is understandable that some country may not have records on some specific indicators, or the records are missing for some years. If we used the data from all countries, we may have too many missing values that makes our results unreliable. Thus, we decided to take a sample of countries that has relatively fewer missing values on the indicators we aimed to use.

*Info comes from: https://data.worldbank.org/about
