# Data transformation

Data for this project is sourced from the following link:   https://datacatalog.worldbank.org/dataset/gender-statistics  
  
The CSV files were downloaded from the "Data & Resources" tab and imported directly into RStudio for processing. The specific steps taken to process the data for visualization differed between the three topics studied for this project: social rights, education, and employment. Since there is information for over 200 regions, the project selected 30 to analyze their changes over time. Out of the 30 selected countries, 5 belonged to each continent. These countries were randomly selected.  
  
The selected countries are:  
North America: Canada, El Salvador, Mexico, Nicaragua, United States  
South America: Argentina, Brazil, Chile, Colombia, Uruguay  
Europe: Belarus, Iceland, Lithuania, Russian Federation, Ukraine  
Asia: China, Japan, Korea, Malaysia, Thailand  
Africa: Rep. Congo, Niger, Nigeria, Tanzania, Zimbabwe  
Oceania: Australia, Fiji, New Zealand, Papua New Guinea, Samoa  
  
For social rights, the dataset has a lot of questions related to the women social rights with binary labels attached. We divided 24 relevant rights into 6 topics: 2 for Finance, 3 for Freedom, 8 for Law, 3 for Marriage, 4 for Job and 4 for Welfare. If the answer to the question is yes, then the label is 1 (otherwise the label is 0). We averaged the binary numbers in each topic to get the averaged score for each topic. We then used the distribution of the scores for individual countries  to analyze social rights issues as presented in the introduction (details are in the check_list.csv at https://github.com/EDAV-Gender-Study-Spring-2021/gender/blob/main/data/check_list.xlsx).
  
For education, we selected indicators that represented the female and male education status across the time like school enrollment and rate of graduation. Moreover, in order to detect the correlation between female education status and other factors, we also selected GDP, fertility rate,  female rural population and government expenditure on education department. To reduce the effect of missing values, we use average scores across multiple years instead of using data from specific year on most of the plot except for the time-series plots.
  
For employment, the specific features selected from the data set included the employment to population ratio of males and females aged 15+ from model ILO estimates, the female share of employment in upper/middle management, the Women business and the law index, and the female/male employment ratio. The Women business and the law index had no missing values. 2010-2019 averages were used for data visualization for the other features where some values were missing. 