# Conclusion

For social rights:    
1.In general, Iceland, Canada and New Zealand do well. No obvious gender discrimination in finance and freedom, but marked gender discrimination is found in social welfare these year.  
2.World started to focus on solving the gender discrimination problem at around 1987. The gender discrimination decreased a lot during last 40 years. And in the law and welfare aspects, the discrimination moderated rapidly yet still exists.  
3.GDP has no influence on the gender discrimination in social rights aspects while the location of the country will, to some extent, determine the gender discrimination condition in social rights aspect. Generally, the North America will have a higher scores in the majority of topics.  
  
For education:  
1. There exists gender discrimination on education opportunities. Even in recent years, share of female graduates from different majors still have big differences.  
2. The education level of women is correlated with both GDP and geographical factor. Countries with high GDP will highly likely to have more education resources and less children in rural area where education resources are more scarce. Countries in North and South America have high scores in female education level shows there may also geographical factor that correlates with gender discrimination on education.  
  
For employment:  
1. There appears to be noticeable employment differences between genders in almost all of the countries sampled for the study. The differences observed stemmed from employment ratios and potentially career opportunities. There was only one case where a country had more females in upper/middle management than males, the others were all heavily skewed towards male.  
2. over the past 30 years, the trends for gender equality in employment has been steadily getting better throughout the world, as suggested by growing Women Business and the Law index scores for every nation selected (though significant discrepancies between nations exist). As for regional or developmental effects on employment ratios, the trends appear unobservable or very weak at best.  
3. There appears to be more correlation between GDP and employment ratios throughout the world, but if you subset to specific continents, an argument can be made that specific continents like Europe and Africa have correlated GDP and female/male labor force participation rates.  

Some limitations:  
1.Owing to the availability of the data, we only sampled 30 countries from different continents in the world. The analysis result may not be representative for the whole world.  
2.The number of social rights questions asked by the dataset provider is not large enough (only 24), so the analysis result may be limited and only can reflect partial conditions of the worldwide social rights for women.  
3.Maybe when more data are available, we can explore more about the same topic (analysis limitation).  
4.The assignment of questions to topics is quite subjective. Maybe there are some better assignments for the questions to the topics.  