--- 
title: "Analyzing Gender Discrepancies Over Time Using Social, Educational, and Employment Trends"
author: "Vincent Chang, Xiaoyan Li, Yaojia Ye"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---

# Introduction

In 2016, the American president election became the most heated topic around the world. On the one hand, the support rates between the Donald Trump and Hillary Diane Rodham Clinton were very close, making the result hard to predict. On the other hand, if the Hillary won the election, she would be the first women president in the American history. It was a pity for Hillary that she did not win the president election eventually but it is noteworthy that an extremely imbalance gender distributions on some specific working fields such as president. Whether the gender discrimination exists worldwide and to what extent does the gender discrimination present seem to be controversial problems and worthy to be explored. In this project, we want to gain a overall perception about the gender discrimination in the world by mainly seeking the answers for three sub-questions through exploratory data analysis:

1: How do women's social status compare to men's social status in modern society from a variety of standpoints like social rights, employment, education, etc.

2: How has women's social status changed in the last 30 years (years data is available for) regarding social rights, employment, education, etc.

3: What are the differences and developments in women's social status between different countries in recent years? Does GDP (or other developmental/ geographical factors) have an influence on equal rights(Or How to explain the status differences from the perspective of differences of countries)?

Owing to the data availability for countries, we used only 30 countries with high quality data to do the analysis, each of them are randomly chosen from 6 continents. We hope the situations in these countries can somehow reflect the whole gender discrimination situations in the whole world.